---
name: bmi160
description: Driver for BMI160 ultra-small, low power, low noise 16 bit IMU
version: 1.0.3
groups:
  - imu
code_owners:
  - lukbieli
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: n/a
targets:
  - esp32
  - esp32c2
  - esp32c3
  - esp32c5
  - esp32c6
  - esp32c61
  - esp32h2
  - esp32p4
  - esp32s2
  - esp32s3
  - esp8266
license: ISC
copyrights:
  - name: lukbieli
    year: 2025
